### ISSUE TITLE
[Mechanics] Incorrect cutout for switches

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-jackbot#29]
The switches have an incorrect cutout, the clips at the sides of the switches wont hold them in place.

Refer here for the correct cutout for the switches
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/mechanics/design.html#_switches

**Comment by karlrahn** [comment]
Fixed the cutouts for switches

**Comment by maidlam** [comment]
The current cutouts will be very tight for the switches.
Make the cutout based on the image below (from mechanics guide).
The 2,5 mm at the bottom of the cutout is made so that the prongs of the switch will engage and fix the switch in place.

![pilt](https://user-images.githubusercontent.com/32770145/204150489-19e6c624-5aba-4f94-82ce-4d7404ba3f2d.png)

**Comment by karlrahn** [comment]
So you suggest that I make it a bit looser?

**Comment by karlrahn** [comment]
Made them looser

**Comment by maidlam** [comment]
Change the bottom height of the cutout to 2,5 mm. That part is important for the switches.
The 11,1 mm and 14,4 mm parts are still not correct and increase the radius to 3,7 mm.

**Comment by karlrahn** [comment]
I left the holes on the smaller cut, but changed the measurements now correctly. Should be ok I guess.
